name: Deploy Stage
on:
  workflow_run:
    workflows: ['Commit Stage']
    types: [ completed ]
    branches: main
concurrency: acceptance


env:
  OWNER: kiwi1020
  REGISTRY: ghcr.io
  APP_REPO: malrang-service
  VERSION: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u kiwi1020 --password-stdin
            docker pull ghcr.io/kiwi1020/kangnengthon-service:latest
            docker stop kangnengthon-app || true
            docker rm kangnengthon-app || true
            docker run -d --name kangnengthon-app -p 8080:8080 -m 512m ghcr.io/kiwi1020/kangnengthon-service:latest
      
